# Generated by Django 3.1.4 on 2021-10-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntrca_app', '0006_auto_20211021_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ntrcacirtificate',
            name='district',
        ),
        migrations.RemoveField(
            model_name='ntrcacirtificate',
            name='division',
        ),
        migrations.RemoveField(
            model_name='ntrcacirtificate',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='ntrcacirtificate',
            name='subject_name',
        ),
        migrations.RemoveField(
            model_name='ntrcacirtificate',
            name='upazila',
        ),
        migrations.RemoveField(
            model_name='ntrcacirtificate',
            name='village',
        ),
        migrations.AddField(
            model_name='ntrcacirtificate',
            name='total_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
