# Generated by Django 3.1.4 on 2021-10-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntrca_app', '0007_auto_20211021_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntrcacirtificate',
            name='subject_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
