# Generated by Django 3.1.4 on 2021-10-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntrca_app', '0008_ntrcacirtificate_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntrcacirtificate',
            name='reg',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
