# Generated by Django 3.1.4 on 2021-10-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntrca_app', '0009_ntrcacirtificate_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ntrcacirtificate',
            name='reg',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
