# Generated by Django 3.1.4 on 2021-10-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntrca_app', '0010_auto_20211021_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntrcacirtificate',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ntrcacirtificate',
            name='gender',
            field=models.PositiveIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Both')], null=True),
        ),
        migrations.AddField(
            model_name='ntrcacirtificate',
            name='nid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ntrcacirtificate',
            name='permanent_dist',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='ntrcacirtificate',
            name='permanent_post',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ntrcacirtificate',
            name='permanent_ps',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='ntrcacirtificate',
            name='permanent_vill',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='ntrcacirtificate',
            name='post_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ntrcacirtificate',
            name='religion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
