# Generated by Django 3.1.4 on 2021-10-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntrca_app', '0011_auto_20211024_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ntrcacirtificate',
            name='permanent_dist',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ntrcacirtificate',
            name='permanent_post',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ntrcacirtificate',
            name='permanent_ps',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ntrcacirtificate',
            name='permanent_vill',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
