# Generated by Django 3.1.4 on 2021-10-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntrca_app', '0013_auto_20211025_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ntrcacirtificate',
            name='nid',
            field=models.BigIntegerField(null=True),
        ),
    ]
