# Generated by Django 3.1.4 on 2021-10-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntrca_app', '0014_auto_20211025_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ntrcacirtificate',
            name='nid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
