# Generated by Django 3.1.4 on 2021-10-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntrca_app', '0015_auto_20211025_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntrcacirtificate',
            name='post_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
