# Generated by Django 3.1.4 on 2021-10-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntrca_app', '0016_ntrcacirtificate_post_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.IntegerField(blank=True, null=True)),
                ('post_code', models.IntegerField(blank=True, null=True)),
                ('post_name', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
