# Generated by Django 3.1.4 on 2021-10-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntrca_app', '0017_postname'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntrcacirtificate',
            name='written_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
