# Generated by Django 3.1.4 on 2021-10-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntrca_app', '0018_ntrcacirtificate_written_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAndSubjectCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255)),
                ('subject_code', models.IntegerField()),
                ('post_code', models.IntegerField()),
                ('post_name', models.CharField(max_length=255)),
                ('institute_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'post_sub_name',
            },
        ),
    ]
