# Generated by Django 3.1.4 on 2021-10-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntrca_app', '0021_studentvaliddata_studentwrongdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.PositiveIntegerField(null=True)),
                ('subject_code', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'total_student',
            },
        ),
    ]
