# Generated by Django 3.1.4 on 2021-10-28 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntrca_app', '0023_auto_20211029_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ntrcacirtificate',
            name='permanent_dist',
        ),
        migrations.RemoveField(
            model_name='ntrcacirtificate',
            name='permanent_post',
        ),
        migrations.RemoveField(
            model_name='ntrcacirtificate',
            name='permanent_ps',
        ),
        migrations.AddField(
            model_name='ntrcacirtificate',
            name='permanent_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permanent_district', to='ntrca_app.district'),
        ),
        migrations.AddField(
            model_name='ntrcacirtificate',
            name='permanent_police_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permanent_thana', to='ntrca_app.thana'),
        ),
        migrations.AddField(
            model_name='ntrcacirtificate',
            name='permanent_post_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permanent_post', to='ntrca_app.postoffice'),
        ),
    ]
