# Generated by Django 3.1.4 on 2021-11-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntrca_app', '0024_auto_20211029_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntrcacirtificate',
            name='viva_mark',
            field=models.IntegerField(null=True),
        ),
    ]
