# Generated by Django 3.1.4 on 2022-01-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntrca_app', '0026_auto_20211103_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ntrcacirtificate',
            name='hsc_result',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ntrcacirtificate',
            name='ssc_result',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ntrcacirtificate',
            name='viva_mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
