# Generated by Django 3.1.4 on 2022-02-03 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ntrca_app', '0029_auto_20220202_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicatecertificate',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ntrcacirtificate',
            name='nid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
