# Generated by Django 3.1.4 on 2022-02-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntrca_app', '0030_auto_20220203_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicatecertificate',
            name='note',
            field=models.TextField(blank=True, default='General', help_text='Duplicate note', null=True),
        ),
    ]
