# Generated by Django 3.1.4 on 2022-07-23 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntrca_app', '0031_auto_20220213_0459'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamsName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('year', models.PositiveIntegerField()),
                ('examth', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='ntrcacirtificate',
            name='exam_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ntrca_app.examsname'),
        ),
        migrations.AddField(
            model_name='ntrcaresult',
            name='exam_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ntrca_result', to='ntrca_app.examsname'),
        ),
    ]
