# Generated by Django 4.0.6 on 2022-08-01 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntrca_app', '0033_examsname_certificate_pass_examsname_viva_pass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NtrcaResult',
        ),
    ]
