# Generated by Django 4.2.9 on 2024-01-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntrca_app', '0036_alter_district_id_alter_duplicatecertificate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsname',
            name='reg_prefixed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
