# Generated by Django 4.2.9 on 2024-01-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntrca_app', '0037_examsname_reg_prefixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsname',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
