# Generated by Django 4.2.9 on 2024-01-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntrca_app', '0038_examsname_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postoffice',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thana',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
