# Generated by Django 4.2.9 on 2024-01-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntrca_app', '0039_district_code_postoffice_code_thana_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ntrcacirtificate',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ntrcacirtificate',
            name='permanent_district',
        ),
        migrations.RemoveField(
            model_name='ntrcacirtificate',
            name='permanent_police_station',
        ),
        migrations.RemoveField(
            model_name='ntrcacirtificate',
            name='permanent_post_office',
        ),
        migrations.RemoveField(
            model_name='ntrcacirtificate',
            name='permanent_vill',
        ),
        migrations.AddField(
            model_name='ntrcacirtificate',
            name='district_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ntrcacirtificate',
            name='police_station_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ntrcacirtificate',
            name='post_office_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
