# Generated by Django 4.2.9 on 2024-01-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntrca_app', '0042_ntrcacirtificate_certificate_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ntrcacirtificate',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
