# Generated by Django 4.2.9 on 2024-01-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntrca_app', '0043_alter_ntrcacirtificate_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ntrcacirtificate',
            name='dob',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
