# Generated by Django 3.1.4 on 2020-12-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.IntegerField()),
                ('interview_date', models.DateField()),
                ('roll', models.IntegerField()),
                ('subject_code', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('father', models.CharField(max_length=200)),
                ('mother', models.CharField(max_length=200)),
                ('s_exam', models.CharField(max_length=20)),
                ('s_result', models.CharField(max_length=20)),
                ('s_result_text', models.CharField(max_length=20)),
                ('h_exam', models.CharField(max_length=20)),
                ('h_result', models.CharField(max_length=20)),
                ('h_result_text', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('invoice', models.CharField(max_length=20)),
            ],
        ),
    ]
