# Generated by Django 3.1.4 on 2022-07-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_auto_20201202_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='h_exam',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='h_result',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='h_result_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='s_exam',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='s_result',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='s_result_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
