# Generated by Django 4.2.9 on 2024-01-14 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntrca_app', '0027_duplicatecertificate_duplicatecertificatefile_and_more'),
        ('candidate', '0003_auto_20201202_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='exam_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_exam_name', to='ntrca_app.examsname'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.PositiveIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Both')], null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='institute_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='nid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='permanent_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district', to='ntrca_app.district'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='permanent_police_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thana', to='ntrca_app.thana'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='permanent_post_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='ntrca_app.postoffice'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='permanent_vill',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='post_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='post_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='reg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='religion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='subject_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='written_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='h_exam',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='h_result',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='h_result_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='s_exam',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='s_result',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='s_result_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
