# Generated by Django 3.1.4 on 2022-07-23 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntrca_app', '0032_auto_20220723_1014'),
        ('candidate', '0004_auto_20220705_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='exam_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ntrca_app.examsname'),
        ),
    ]
